apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-secret-app-deployment
  labels:
    app: python-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-secret-app
  template:
    metadata:
      labels:
        app: python-secret-app
    spec:
      serviceAccountName: nginx-deployment-sa
      volumes: 
        - name: db-creds
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: db-aws-secrets 
      containers:
      - name: python-secret-app
        image: kiran63/secretk8sapp:latest
        volumeMounts:
          - name: db-creds
            mountPath: /tmp  # Mounting secret to /tmp
        ports:
        - containerPort: 5000

